### ISSUE TITLE
Sysinfo cannot detect EclipseOS

### ISSUE THREAD

**Issue by atenefyr** [dannysmc95/EclipseOS#1]
I've moved over SysInfo dynamic testing to osdata, but the thing, is sysinfo can't access the osdata table set by your OS because it's intended to be loaded as an API (which is in it's own environment).
Making the osdata table in _G (_G.osdata) would allow sysinfo to detect EclipseOS with ease.

**Comment by dannysmc95** [comment]
I have no actually finished this OS, it is far off finished :P I have a little while to go. But thanks I did wonder!

**Comment by atenefyr** [comment]
That doesn't mean I can't provide some feedback :P
